export const BANNERS_REQUEST = 'BANNERS_REQUEST';
export const BANNERS_RECEIVE = 'BANNERS_RECEIVE';
export const BANNERS_FAILURE = 'BANNERS_FAILURE';

export const BANNERS_SELECT = 'BANNERS_SELECT';
export const BANNERS_DESELECT = 'BANNERS_DESELECT';

export const BANNER_UPDATE_REQUEST = 'BANNER_UPDATE_REQUEST';
export const BANNER_UPDATE_SUCCESS = 'BANNER_UPDATE_SUCCESS';
export const BANNER_UPDATE_FAILURE = 'BANNER_UPDATE_FAILURE';

export const BANNER_CREATE_SUCCESS = 'BANNER_CREATE_SUCCESS';
export const BANNER_DELETE_SUCCESS = 'BANNER_DELETE_SUCCESS';
export const BANNER_MOVE_UPDOWN_SUCCESS = 'BANNER_MOVE_UPDOWN_SUCCESS';
export const BANNER_REPLACE_SUCCESS = 'BANNER_REPLACE_SUCCESS';

export const BANNER_IMAGE_UPLOAD_START = 'BANNER_IMAGE_UPLOAD_START';
export const BANNER_IMAGE_UPLOAD_END = 'BANNER_IMAGE_UPLOAD_END';
