export const ENQUIRIES_REQUEST = 'ENQUIRIES_REQUEST';
export const ENQUIRIES_RECEIVE = 'ENQUIRIES_RECEIVE';

export const ENQUIRY_SELECT = 'ENQUIRY_SELECT';
export const ENQUIRY_DESELECT = 'ENQUIRY_DESELECT';
export const ENQUIRY_DESELECT_ALL = 'ENQUIRY_DESELECT_ALL';
export const ENQUIRY_SELECT_ALL = 'ENQUIRY_SELECT_ALL';

export const ENQUIRY_DELETE_SUCCESS = 'ENQUIRY_DELETE_SUCCESS';

export const CONTACT_VIEW = 'CONTACT_VIEW';
