export const BRANDS_REQUEST = 'BRANDS_REQUEST';
export const BRANDS_RECEIVE = 'BRANDS_RECEIVE';
export const BRANDS_FAILURE = 'BRANDS_FAILURE';

export const BRANDS_SELECT = 'BRANDS_SELECT';
export const BRANDS_DESELECT = 'BRANDS_DESELECT';

export const BRAND_UPDATE_REQUEST = 'BRAND_UPDATE_REQUEST';
export const BRAND_UPDATE_SUCCESS = 'BRAND_UPDATE_SUCCESS';
export const BRAND_UPDATE_FAILURE = 'BRAND_UPDATE_FAILURE';

export const BRAND_CREATE_SUCCESS = 'BRAND_CREATE_SUCCESS';
export const BRAND_DELETE_SUCCESS = 'BRAND_DELETE_SUCCESS';
export const BRAND_MOVE_UPDOWN_SUCCESS = 'BRAND_MOVE_UPDOWN_SUCCESS';
export const BRAND_REPLACE_SUCCESS = 'BRAND_REPLACE_SUCCESS';

export const BRAND_IMAGE_UPLOAD_START = 'BRAND_IMAGE_UPLOAD_START';
export const BRAND_IMAGE_UPLOAD_END = 'BRAND_IMAGE_UPLOAD_END';
