export const CONTACTUS_REQUEST = 'CONTACTUS_REQUEST';
export const CONTACTUS_RECEIVE = 'CONTACTUS_RECEIVE';
export const CONTACTUS_SELECT = 'CONTACTUS_SELECT';
export const CONTACTUS_DESELECT = 'CONTACTUS_DESELECT';
export const CONTACTUS_DESELECT_ALL = 'CONTACTUS_DESELECT_ALL';
export const CONTACTUS_SELECT_ALL = 'CONTACTUS_SELECT_ALL';
export const CONTACTUS_DELETE_SUCCESS = 'CONTACTUS_DELETE_SUCCESS';
export const CONTACT_VIEW = 'CONTACT_VIEW';
